version: "3.5"
services:
  mongo:
    image: mongo:4.2.1
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db # 挂载数据目录
      - ./mongo/log:/var/log/mongodb  # 挂载日志目录
    privileged: true  # 设置容器的权限为root
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # 账号
      MONGO_INITDB_ROOT_PASSWORD: root123456
networks:
  docker:
    external: true