// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v3.17.3
// source: moralis/v1/stream.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStreamReceive = "/api.moralis.v1.Stream/Receive"

type StreamHTTPServer interface {
	Receive(context.Context, *ReceiveRequest) (*ReceiveReply, error)
}

func RegisterStreamHTTPServer(s *http.Server, srv StreamHTTPServer) {
	r := s.Route("/")
	r.POST("/stream/receive", _Stream_Receive0_HTTP_Handler(srv))
}

func _Stream_Receive0_HTTP_Handler(srv StreamHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReceiveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStreamReceive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Receive(ctx, req.(*ReceiveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReceiveReply)
		return ctx.Result(200, reply)
	}
}

type StreamHTTPClient interface {
	Receive(ctx context.Context, req *ReceiveRequest, opts ...http.CallOption) (rsp *ReceiveReply, err error)
}

type StreamHTTPClientImpl struct {
	cc *http.Client
}

func NewStreamHTTPClient(client *http.Client) StreamHTTPClient {
	return &StreamHTTPClientImpl{client}
}

func (c *StreamHTTPClientImpl) Receive(ctx context.Context, in *ReceiveRequest, opts ...http.CallOption) (*ReceiveReply, error) {
	var out ReceiveReply
	pattern := "/stream/receive"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStreamReceive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
