server:
  http:
    addr: 127.0.0.1:18000
    timeout: 1s
#  grpc:
#    addr: 127.0.0.1:19000
#    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  mongodb:
    url: mongodb://117.72.12.178:27017
    username: root
    password: root123456
    minPoolSize: 10
    maxPoolSize: 100
    db: MarketPlace
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

moralis:
  url: https://deep-index.moralis.io/api/v2.2/nft/
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6Ijk4OTUwNzhhLWRjMjItNDE1MC05NmRlLTc2YmZmYzE1OGJjOCIsIm9yZ0lkIjoiMzg0NTg1IiwidXNlcklkIjoiMzk1MTU5IiwidHlwZUlkIjoiOTYyOGIwMzktMGZhOC00ZTM4LWE3OGUtZDgwNDBhYThiNjMzIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MTEzNDgxMTEsImV4cCI6NDg2NzEwODExMX0.omhHgc-MeZxX3AQDFAQWGqG9lXLN0xMDnwxYBhC2lGk