server:
  http:
    addr: 127.0.0.1:18000
    timeout: 1s
#  grpc:
#    addr: 127.0.0.1:19000
#    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  mongo:
    url: mongodb://192.168.2.128:27018
    username: MarketPlace
    password: 12qwaszx
    minPoolSize: 10
    maxPoolSize: 100
    db: MarketPlace
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
